Fix handling of exceptions when osquery goes away
osquery/osquery-python pull request #83
Opened 2022-04-12 18:12 UTC by zwass

This resolves an issue where the extension does not shut down if osquery
goes away unexpectedly (without sending a shutdown signal via Thrift).

The scenario could be reliably reproduced by running `osqueryi`,
connecting an extension, and then sending a `SIGKILL` to `osqueryi`. The
exception thrown in the `start_watcher` function would be of type
`thrift.transport.TTransport.TTransportException`, and would cause the
watcher thread to exit without exiting the rest of the program.

This is a possible fix for issues that users have experienced with
extensions reconnecting after the Watchdog kills osquery.

2022-04-12 18:44 UTC, sharvilshah requested changes
I think we will need to update the version in https://github.com/osquery/osquery-python/blob/master/osquery/__init__.py#L7 too?

2022-04-15 00:05 UTC, zwass commented
I'd prefer to keep those version updates in a separate PR (https://github.com/osquery/osquery-python/pull/84). @sharvilshah does that work for you?

2022-04-15 05:48 UTC, sharvilshah commented
That works!

2022-04-15 05:48 UTC, sharvilshah approved these changes

2022-04-15 15:55 UTC, merged